#!/usr/bin/env python3
"""
Discover a SaaS need and create a GitHub issue describing the MVP task.

Uses the day-of-year to cycle deterministically through a curated list of
MVP ideas relevant to the AlternaGen platform.
"""

import datetime
import os

import requests

REPO = os.environ["REPO"]
GH_TOKEN = os.environ["GH_TOKEN"]
API_BASE = "https://api.github.com"

HEADERS = {
    "Authorization": f"Bearer {GH_TOKEN}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}

MVP_IDEAS = [
    {
        "title": "MVP: Auto-matching algorithm based on student skills and job requirements",
        "body": (
            "## 💡 Need Discovered\n\n"
            "Students struggle to find relevant alternance offers that match their skill set.\n\n"
            "## 🎯 MVP Objective\n\n"
            "Build an auto-matching algorithm that scores job offers against a student profile.\n\n"
            "## ✅ Acceptance Criteria\n\n"
            "- [ ] Parse student profile (skills, location, availability)\n"
            "- [ ] Score each job offer with a relevance percentage\n"
            "- [ ] Expose a `/match` API endpoint\n"
            "- [ ] Return top 10 ranked offers\n"
        ),
    },
    {
        "title": "MVP: Email digest of new alternance offers",
        "body": (
            "## 💡 Need Discovered\n\n"
            "Students miss new job offers because they don't visit the platform daily.\n\n"
            "## 🎯 MVP Objective\n\n"
            "Send a daily email digest of new matching alternance offers.\n\n"
            "## ✅ Acceptance Criteria\n\n"
            "- [ ] Query new offers posted in the last 24 hours\n"
            "- [ ] Filter by student preferences\n"
            "- [ ] Send HTML email via SendGrid or similar\n"
            "- [ ] Provide unsubscribe link\n"
        ),
    },
    {
        "title": "MVP: Browser extension one-click job save",
        "body": (
            "## 💡 Need Discovered\n\n"
            "Students find interesting offers on external sites but lose track of them.\n\n"
            "## 🎯 MVP Objective\n\n"
            "Enhance the browser extension to save job listings with one click from any job board.\n\n"
            "## ✅ Acceptance Criteria\n\n"
            "- [ ] Detect job listing pages on major boards (LinkedIn, Indeed, APEC)\n"
            "- [ ] Extract title, company, location, description\n"
            "- [ ] Save to AlternaGen via API\n"
            "- [ ] Show confirmation toast\n"
        ),
    },
    {
        "title": "MVP: AI-powered CV feedback module",
        "body": (
            "## 💡 Need Discovered\n\n"
            "Students submit CVs that are not optimised for the alternance market.\n\n"
            "## 🎯 MVP Objective\n\n"
            "Build an AI module that analyses uploaded CVs and returns actionable feedback.\n\n"
            "## ✅ Acceptance Criteria\n\n"
            "- [ ] Accept PDF CV upload\n"
            "- [ ] Extract text and analyse with OpenAI\n"
            "- [ ] Return structured feedback (score, missing keywords, format tips)\n"
            "- [ ] Display results in the dashboard\n"
        ),
    },
    {
        "title": "MVP: Company dashboard to post and manage alternance offers",
        "body": (
            "## 💡 Need Discovered\n\n"
            "Companies lack a simple interface to post and track their alternance offers.\n\n"
            "## 🎯 MVP Objective\n\n"
            "Create a company-facing dashboard for posting and managing job offers.\n\n"
            "## ✅ Acceptance Criteria\n\n"
            "- [ ] Company sign-up / login flow\n"
            "- [ ] CRUD for job offers\n"
            "- [ ] View list of applicants per offer\n"
            "- [ ] Export applicant data as CSV\n"
        ),
    },
]


def create_issue(title: str, body: str) -> dict:
    url = f"{API_BASE}/repos/{REPO}/issues"
    payload = {
        "title": title,
        "body": body,
        "labels": ["autosaas", "mvp"],
    }
    response = requests.post(url, headers=HEADERS, json=payload, timeout=30)
    response.raise_for_status()
    return response.json()


def main() -> None:
    today = datetime.date.today()
    # Cycle deterministically through ideas based on day-of-year (0-indexed)
    idea = MVP_IDEAS[(today.timetuple().tm_yday - 1) % len(MVP_IDEAS)]

    dated_title = f"[AutoSaaS {today.isoformat()}] {idea['title']}"
    dated_body = (
        f"> 🤖 Auto-generated by AutoSaaS workflow on {today.isoformat()}\n\n"
        + idea["body"]
    )

    issue = create_issue(dated_title, dated_body)
    print(f"✅ Issue created: #{issue['number']} — {issue['html_url']}")


if __name__ == "__main__":
    main()
